Mvc/Controllers/EmployeeController.cs
using Domain.Entities;
using Domain.Interfaces.InterfacesServices;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Mvc.Areas.Identity.Data;

namespace Mvc.Controllers
{
    public class EmployeeController : Controller
    {
        private readonly IEmployeeService _employeeService;
        private readonly UserManager<UserModel> _userManager;
        private readonly IUserStore<UserModel> _userStore;
        private readonly IUserEmailStore<UserModel> _emailStore;

        public EmployeeController(IEmployeeService employeeService,
                                  UserManager<UserModel> userManager,
                                  IUserStore<UserModel> userStore)
        {
            _employeeService = employeeService;
            _userManager = userManager;
            _userStore = userStore;
            _emailStore = (IUserEmailStore<UserModel>)userStore;
        }

        // Listagem de funcionários
        public async Task<IActionResult> Index()
        {
            var employees = await _employeeService.GetAll();

            // Converter a lista de Domain.Entities.Employee para uma lista de Models.Employee
            var employeeViewModels = employees.Select(employee => new Models.Employee
            {
                Id = employee.Id,
                Name = employee.Name,
                Function = (Models.Enums.EnumFunctionEmployee)employee.Function
            }).ToList();

            return View(employeeViewModels);
        }

        // GET: Create
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(Employee employee)
        {
            if (ModelState.IsValid)
            {
                // Criar um novo usuário no Identity
                var user = new UserModel
                {
                    UserName = employee.Email,
                    Email = employee.Email,
                    Name = employee.Name
                };

                await _userStore.SetUserNameAsync(user, employee.Email, CancellationToken.None);
                await _emailStore.SetEmailAsync(user, employee.Email, CancellationToken.None);

                var result = await _userManager.CreateAsync(user, employee.Password);

                if (result.Succeeded)
                {
                    // Após adicionar no Identity, adicionar o funcionário na tabela Employees
                    await _employeeService.Add(employee);

                    // Adicionar o funcionário no papel (role) específico
                    await _userManager.AddToRoleAsync(user, "Admin");

                    return RedirectToAction(nameof(Index));
                }

                foreach (var error in result.Errors)
                {
                    ModelState.AddModelError(string.Empty, error.Description);
                }
            }

            return RedirectToAction(nameof(Index));
        }

    // GET: Details
    public async Task<IActionResult> Details(int id)
        {
            var employee = await _employeeService.GetById(id);
            if (employee == null)
            {
                return NotFound();
            }
            return View(employee);
        }

        // GET: Edit
        public async Task<IActionResult> Edit(int id)
        {
            var employee = await _employeeService.GetById(id);
            if (employee == null)
            {
                return NotFound();
            }
            Models.Employee employeeView = new Models.Employee
            {
                Id = employee.Id,
                Name = employee.Name,
                Function = (Models.Enums.EnumFunctionEmployee)employee.Function
            };
            return View(employeeView);
        }

        // POST: Edit
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, Employee employee)
        {
            if (id != employee.Id)
            {
                return NotFound();
            }

                Domain.Entities.Employee employee1 = new Domain.Entities.Employee
                {
                    Id = employee.Id,
                    Name = employee.Name,
                    Password = employee.Password,
                    Function = (Domain.Entities.Enums.EnumFunctionEmployee)employee.Function
                };
                var result = await _employeeService.Update(employee1);
                return RedirectToAction(nameof(Index));
            
        }

        // GET: Delete
        public async Task<IActionResult> Delete(int id)
        {
            var employee = await _employeeService.GetById(id);
            if (employee == null)
            {
                return NotFound();
            }
            Models.Employee employeeView = new Models.Employee
            {
                Id = employee.Id,
                Name = employee.Name,
                Function = (Models.Enums.EnumFunctionEmployee)employee.Function
            };
            return View(employeeView);
        }

        // POST: Delete
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            await _employeeService.Delete(id);
            return RedirectToAction(nameof(Index));
        }
    }
}

Mvc/Controllers/ManagerController.cs
using Domain.Entities;
using Domain.Interfaces.InterfacesServices;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Mvc.Models;

namespace Mvc.Controllers
{
    public class ManagerController : Controller
    {
        private readonly ISaleService _saleService;
        private readonly ISaleProductService _saleProductService;

        public ManagerController(ISaleService saleService, ISaleProductService saleProductService)
        {
            _saleService = saleService;
            _saleProductService = saleProductService;
        }

        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Index()
        {
            var saleProductsViewModel = await GetAll();

            return View(saleProductsViewModel);
        }

        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> All()
        {
            var saleProductsViewModel = await GetAll();

            return View(saleProductsViewModel);
        }

        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Delivering()
        {
            var saleProductsViewModel = await GetAll();

            return View(saleProductsViewModel);
        }

        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Unpaid()
        {
            var saleProductsViewModel = await GetAll();

            return View(saleProductsViewModel);
        }

        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Terminated()
        {
            var saleProductsViewModel = await GetAll();

            return View(saleProductsViewModel);
        }

        [HttpPost]
        public async Task<IActionResult> ChangeStatusSale(int SaleId, Models.Enums.EnumStatusSale StatusSale)
        {
            var result = await _saleService.GetById(SaleId);
            if (result == null)
            {
                return NotFound();
            }

            result.StatusSale = (Domain.Entities.Enums.EnumStatusSale)StatusSale;
            var response = await _saleService.Update(result, new List<SaleProduct>());

            return RedirectToAction("Index");
        }

        [HttpPost]
        public async Task<IActionResult> ChangeStatusPayment(int SaleId, Models.Enums.EnumStatusPayment StatusPayment)
        {
            var result = await _saleService.GetById(SaleId);
            if (result == null)
            {
                return NotFound();
            }

            result.StatusPayment = (Domain.Entities.Enums.EnumStatusPayment)StatusPayment;
            var response = await _saleService.Update(result, new List<SaleProduct>());

            return RedirectToAction("Index");
        }

        [HttpPost]
        public async Task<IActionResult> ChangeTypePayment(int SaleId, Models.Enums.EnumTypePayment TypePayment)
        {
            var result = await _saleService.GetById(SaleId);
            if (result == null)
            {
                return NotFound();
            }

            result.TypePayment = (Domain.Entities.Enums.EnumTypePayment)TypePayment;
            var response = await _saleService.Update(result, new List<SaleProduct>());

            return RedirectToAction("Index");
        }

        public async Task<List<Models.Sale>> GetAll()
        {
            var result = await _saleService.GetAll();

            var saleProductsViewModel = new List<Models.Sale>();

            foreach (var sale in result)
            {
                var saleViewModel = new Models.Sale
                {
                    Id = sale.Id,
                    SaleDate = sale.SaleDate,
                    ClientId = sale.ClientId,
                    ClientName = sale.Client.Name,
                    PhoneNumber = sale.Client.PhoneNumber,
                    TotalValue = sale.TotalValue,
                    TypePayment = (Models.Enums.EnumTypePayment)sale.TypePayment,
                    StatusSale = (Models.Enums.EnumStatusSale)sale.StatusSale,
                    StatusPayment = (Models.Enums.EnumStatusPayment)sale.StatusPayment,
                    Discount = sale.Discount,
                    EmployeeId = sale.EmployeeId,
                    EmployeeName = sale.Employee.Name,
                    SaleProductsName = new List<string>()
                };

                var resultProducts = await _saleProductService.GetBySale(sale.Id);

                foreach (var saleProduct in resultProducts)
                {
                    saleViewModel.SaleProductsName.Add(saleProduct.Product.Name);
                }

                saleProductsViewModel.Add(saleViewModel);
            }
            return saleProductsViewModel;
        }
    }
}

Mvc/Controllers/MaterialController.cs
using Domain.Interfaces.InterfacesServices;
using Microsoft.AspNetCore.Mvc;

namespace Mvc.Controllers
{
    public class MaterialController : Controller
    {
        private readonly IMaterialService _materialService;

        public MaterialController(IMaterialService materialService)
        {
            _materialService = materialService;
        }

        public async Task<IActionResult> Index()
        {
            var materials = await _materialService.GetAll();
            var materialsView = materials.Select(material => new Models.Material
            {
                Id = material.Id,
                Name = material.Name,
                PurchasePrice = material.PurchasePrice,
                MinimumQuantity = material.MinimumQuantity,
                Amount = material.Amount
            }).ToList();

            return View(materialsView);
        }

        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Create(Models.Material material)
        {
            try
            {
                material.PurchasePrice = Convert.ToDecimal(material.PurchasePrice);
            }
            catch (Exception)
            {
                ModelState.AddModelError("Preço", "O campo preço deve ser um número decimal");
            }

            if (ModelState.IsValid)
            {
                var materialDomain = new Domain.Entities.Material
                {
                    Name = material.Name,
                    PurchasePrice = material.PurchasePrice,
                    MinimumQuantity = material.MinimumQuantity,
                    Amount = material.Amount
                };

                await _materialService.Add(materialDomain);
                return RedirectToAction("Index");
            }

            return View(material);
        }

        [HttpPost]
        public async Task<IActionResult> CreateInIngredients(Models.Material material)
        {
            //pegar o id do produto passado por parametro
            int productId = Convert.ToInt32(RouteData.Values["id"]);
            try
            {
                material.PurchasePrice = Convert.ToDecimal(material.PurchasePrice);
            }
            catch (Exception)
            {
                ModelState.AddModelError("Preço", "O campo preço deve ser um número decimal");
            }

            if (ModelState.IsValid)
            {
                var materialDomain = new Domain.Entities.Material
                {
                    Name = material.Name,
                    PurchasePrice = material.PurchasePrice,
                    MinimumQuantity = material.MinimumQuantity,
                    Amount = material.Amount
                };

                await _materialService.Add(materialDomain);
                return RedirectToAction("AddIngredients", "Ingredients", new { productId = productId });
            }

            return RedirectToAction("AddIngredients", "Ingredients", new { productId = productId });
        }

        public async Task<IActionResult> Edit(int id)
        {
            var material = await _materialService.GetById(id);
            if (material == null)
            {
                return NotFound();
            }

            var materialView = new Models.Material
            {
                Id = material.Id,
                Name = material.Name,
                PurchasePrice = material.PurchasePrice,
                MinimumQuantity = material.MinimumQuantity,
                Amount = material.Amount
            };

            return View(materialView);
        }

        [HttpPost]
        public async Task<IActionResult> Edit(Models.Material material)
        {
            try
            {
                material.PurchasePrice = Convert.ToDecimal(material.PurchasePrice);
            }
            catch (Exception)
            {
                ModelState.AddModelError("Preço", "O campo preço deve ser um número decimal");
            }

            if (ModelState.IsValid)
            {
                var materialDomain = new Domain.Entities.Material
                {
                    Id = material.Id,
                    Name = material.Name,
                    PurchasePrice = material.PurchasePrice,
                    MinimumQuantity = material.MinimumQuantity,
                    Amount = material.Amount
                };

                var result = await _materialService.Update(materialDomain);
                return RedirectToAction("Index");
            }

            return View(material);
        }

        public async Task<IActionResult> Delete(int id)
        {
            var material = await _materialService.GetById(id);
            if (material == null)
            {
                return NotFound();
            }

            var materialView = new Models.Material
            {
                Id = material.Id,
                Name = material.Name,
                PurchasePrice = material.PurchasePrice,
                MinimumQuantity = material.MinimumQuantity,
                Amount = material.Amount
            };

            return View(materialView);
        }

        [HttpPost]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            await _materialService.Delete(id);
            return RedirectToAction("Index");
        }
    }
}

Mvc/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Mvc</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Mvc.styles.css" asp-append-version="true" />
</head>
<body style="margin:20px 0; padding:0; background-color:@((User.IsInRole("Admin")) ? "white" : "black")">
    <div class="container @((User.IsInRole("Admin")) ? "admin-background" : "")">
    <header>
            <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light  border-bottom box-shadow mb-3 container @((User.IsInRole("Admin")) ? "admin-background" : "")">
            <div class="container-fluid">
                    <a class="navbar-brand text-light @((User.IsInRole("Admin")) ? "text-dark" : "")" asp-area="" asp-controller="Home" asp-action="Index">App-Burguer</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                
            </div>
            <div>
                @if (User.Identity.IsAuthenticated && User.IsInRole("Admin"))
                {
                    <div class="btn-group">
                        <!-- Pedidos Dropdown -->
                        <div class="dropdown">
                            <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownPedidos" data-bs-toggle="dropdown" aria-expanded="false">
                                Pedidos
                            </button>
                            <ul class="dropdown-menu" aria-labelledby="dropdownPedidos">
                                <li><a class="dropdown-item" asp-controller="Manager" asp-action="Index">Pendente</a></li>
                                <li><a class="dropdown-item" asp-controller="Manager" asp-action="Delivering">Entregando</a></li>
                                <li><a class="dropdown-item" asp-controller="Manager" asp-action="Unpaid">Não Pago</a></li>
                                <li><a class="dropdown-item" asp-controller="Manager" asp-action="Terminated">Finalizado</a></li>
                                <li><a class="dropdown-item" asp-controller="Manager" asp-action="All">Todos</a></li>
                            </ul>
                        </div>

                        <!-- Produtos Dropdown -->
                        <div class="dropdown">
                            <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownProducts" data-bs-toggle="dropdown" aria-expanded="false">
                                Produtos
                            </button>
                            <ul class="dropdown-menu" aria-labelledby="dropdownProdutos">
                                <li><a class="dropdown-item" asp-controller="Product" asp-action="Index">Ver Produtos</a></li>
                                <li><a class="dropdown-item" asp-controller="Product" asp-action="Create">Adicionar Produto</a></li>
                            </ul>
                        </div>

                        <!-- Materiais Dropdown -->
                        <div class="dropdown">
                            <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownProducts" data-bs-toggle="dropdown" aria-expanded="false">
                                Materiais
                            </button>
                            <ul class="dropdown-menu" aria-labelledby="dropdownProdutos">
                                <li><a class="dropdown-item" asp-controller="Material" asp-action="Index">Ver Materiais</a></li>
                                <li><a class="dropdown-item" asp-controller="Material" asp-action="Create">Adicionar Material</a></li>
                            </ul>
                        </div>

                        <!-- Clientes Dropdown -->
                        <div class="dropdown">
                            <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownEmplyees" data-bs-toggle="dropdown" aria-expanded="false">
                                Funcionários
                            </button>
                            <ul class="dropdown-menu" aria-labelledby="dropdownEmplyees">
                                <li><a class="dropdown-item" asp-controller="Employee" asp-action="Index">Lista de Funcionários</a></li>
                                <li><a class="dropdown-item" asp-controller="Employee" asp-action="Create">Adicionar Funcionário</a></li>
                            </ul>
                        </div>
                </div>
                }
            </div>
                
                @Html.Partial("_LoginPartial")



                <a asp-controller="Purchase" asp-action="index" class="mx-3" style="color: #fff;">
                    <i class="bi bi-cart"></i>
                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-cart"  viewBox="0 0 16 16">
                    <path d="M0 1.5A.5.5 0 0 1 .5 1H2a.5.5 0 0 1 .485.379L2.89 3H14.5a.5.5 0 0 1 .491.592l-1.5 8A.5.5 0 0 1 13 12H4a.5.5 0 0 1-.491-.408L2.01 3.607 1.61 2H.5a.5.5 0 0 1-.5-.5M3.102 4l1.313 7h8.17l1.313-7zM5 12a2 2 0 1 0 0 4 2 2 0 0 0 0-4m7 0a2 2 0 1 0 0 4 2 2 0 0 0 0-4m-7 1a1 1 0 1 1 0 2 1 1 0 0 1 0-2m7 0a1 1 0 1 1 0 2 1 1 0 0 1 0-2" />
                </svg>
            </a>
        </nav>
    </header>
        <div class="container @((User.IsInRole("Admin")) ? "admin-background" : "")">
            <main role="main" class="container @((User.IsInRole("Admin")) ? "admin-background" : "")">
            @RenderBody()
        </main>
    </div>

        <footer class="border-top footer text-muted " style="position:relative">
            <div class="container @((User.IsInRole("Admin")) ? "admin-background" : "")">
            &copy; 2024 - Mvc - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
    </div>
</body>
</html>